---
- name: Test custmo modules
  hosts: localhost
  gather_facts: False
  tasks:
    - name: hello_old_style (now a file operation)
      hello_old_style:
        some_file: "/tmp/foobar"

    - name: hello_want_json
      hello_want_json:
        name: "Ansible Fort Worth Meetup"

    - name: hello_binary
      hello_binary:
        name: "Ansible Fort Worth Meetup"

    - name: hello_new_style
      hello_new_style:
        name: "Ansible Fort Worth Meetup"
